######################################################################
# Automatically generated by qmake (2.01a) Wed May 4 18:37:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
LIBS += -lglut -lpthread -lGL
OBJECTS_DIR = obj

# Input
HEADERS += Box.hxx Ren.hxx Particle.hxx 
SOURCES += main.cxx Ren.cxx Particle.cxx Box.cxx
